### ISSUE TITLE
sticky header can't move down when first item is a sticky header

### ISSUE THREAD

**Issue by iloveaman** [bgogetap/StickyHeaders#10]
i found another bug :
```
private List<Item> compileItems() {
        List<Item> items = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            if (i % 4 == 0 /*&& i > 0*/) {
                items.add(new HeaderItem("Header at " + i, ""));
            } else {
                items.add(new Item("Item at " + i, "Item description at " + i));
            }
        }
        return items;
    }
```

**Comment by bgogetap** [comment]
Can you explain a little more what you mean here? I made the first item a sticky header in the demo (by taking out the '&& i > 0' part of the conditional like you show) and everything still works as expected (first item sticks to top until next header moves it out of the way).

**Comment by bgogetap** [comment]
Everything seems to work as expected. If you can be more specific on what you think is broken, I'll look into it.
