### ISSUE TITLE
JCenter Deprecation

### ISSUE THREAD

**Issue by barnhill** [bgogetap/StickyHeaders#102]
JCenter is being deprecated May 1, 2021.  This library will need to have its artifacts moved to MavenCentral or some other maven repository.

**Comment by bgogetap** [comment]
Thanks for the reminder. I will make sure to have it available elsewhere before that date.

**Comment by moetouban** [comment]
hey @bgogetap we would like to remove jCenter from our code and would like get an update on when would this library be moved to somewhere else ?

**Comment by bgogetap** [comment]
Working on setting up support for pushing to Maven Central. I'll update when this is complete.

**Comment by bgogetap** [comment]
Alright, 0.6.2 is now available in maven central.
