### ISSUE TITLE
how to  use  custom  sticky header ?

### ISSUE THREAD

**Issue by iloveaman** [bgogetap/StickyHeaders#11]
how to  use  custom  sticky header ?

**Comment by bgogetap** [comment]
What do you mean? Just a different view than the ones used by other items in your RecyclerView? However your would normally setup headers should work, just make the items in your data set that you want to be sticky implement the marker interface StickyHeader.

**Comment by bgogetap** [comment]
Going to close this for now. If you are having a specific issue let me know.
