### ISSUE TITLE
Pinned item not updated when notifyDataSetChange on adapter

### ISSUE THREAD

**Issue by dvdciri** [bgogetap/StickyHeaders#16]
For my implementation of the library i need to change the content of the RecyclerView ofter, so I've implemented an adapter that simply refresh the data when needed and call notifyDataSetChange(). It works, but is not refreshing the pinned item attached on the top screen, is only updating it when it goes outside of the screen (and the recyclerView refresh it).

I've tried with notifyRangeChanged and others but still the same result.

After I'm updating the reference to the list inside my adapter, I'm getting that new list of items and passing it into the StickyHeaderHandler (getAdapterData) in order to keep it updated.. 
So the steps that i'm doing are:
- Instantiate the adapter with empty array list of data
- The StickyHeaderHandler gets the same empty array list of data from the adapter
- New data comes; adapter: clear the list ->addAll -> notify()
- The StickyHeaderHandler gets the new array list of data from the adapter

Those steps works, but the pinned item is the only one not been refreshed properly.

First entry set:
<img src="https://cloud.githubusercontent.com/assets/3275819/17873986/a145134a-68c0-11e6-948d-1ac153a2f42b.png" width="100">

Changing entry set the first item is not up to date 'Header 0 (7)':
<img src="https://cloud.githubusercontent.com/assets/3275819/17874125/8a2f8798-68c1-11e6-8ea5-7f52930f9bd4.png" width="100">

Changin again not up to date:
<img src="https://cloud.githubusercontent.com/assets/3275819/17874108/7455f8f8-68c1-11e6-8c0e-7f5ca7023e06.png" width="100">

After scrolling:
<img src="https://cloud.githubusercontent.com/assets/3275819/17874147/9f571db6-68c1-11e6-9c14-618bba3d10a0.png" width="100">

**Comment by bgogetap** [comment]
I see, so the same header position is bound, but its model has changed. Currently I'm only attaching the header view if the last bound position is different. I may have to give up some efficiency there to cover this case.

I will look into this one, thanks!

**Comment by dvdciri** [comment]
Cool, thanks it works great!
