### ISSUE TITLE
Not sticky header

### ISSUE THREAD

**Issue by notnotme** [bgogetap/StickyHeaders#21]
Hello.

The issue is when the gap between 2 header items is too huge. The next header will not stick if you have too much regular items after the first header.

Version 0.3.0 fix the issue.

**Comment by bgogetap** [comment]
Thanks, I was able to reproduce it. I will look at it tonight or tomorrow.

**Comment by bgogetap** [comment]
Thanks for reporting the issue! Should be resolved in 0.3.3.
