### ISSUE TITLE
Is it possible to add sticky footers? 

### ISSUE THREAD

**Issue by DalveerSinghDaiya** [bgogetap/StickyHeaders#27]

**Comment by bgogetap** [comment]
Yeah that shouldn't be too big of a deal. I'll look into it this week.

**Comment by DalveerSinghDaiya** [comment]
Thank You :)

**Comment by bgogetap** [comment]
Haven't gotten to this yet but it isn't completely off my radar. If anyone is interested in contributing, feel free.

**Comment by bgogetap** [comment]
Closing this as I don't see a need for sticky footers since the effect can be achieved by simply adding a view to your parent layout that has bottom gravity. If there is a use case I'm missing, feel free to comment.
