### ISSUE TITLE
Header's decorators are not also sticky.

### ISSUE THREAD

**Issue by tir38** [bgogetap/StickyHeaders#30]
I've setup a recycler view to use the StickyHeaderAdapter. It's working perfectly. However when I then add an ItemDecoration to the recycler view, the item decorations on the header do not stick with the header. 

```
MyAdapter adapter = new MyAdapter(); // implements StickyHeaderHandler
recyclerView.setAdapter(adapter);
recyclerView.setLayoutManager(new StickyLayoutManager(getContext(), adapter));
Drawable dividerDrawable = ContextCompat.getDrawable(getContext(), R.drawable.line_divider);
recyclerView.addItemDecoration(new DividerItemDecoration(dividerDrawable));
```
I'm using a library for the item decoration, instead of rolling my own, but that shouldn't make a difference.

![example](https://cloud.githubusercontent.com/assets/1980553/23866458/479513ee-07ef-11e7-855a-9ee4e92df6b7.gif)

**Comment by szugyi** [comment]
Based on the way ItemDecorations work I doubt that this issue can be easily resolved with the current implementation of the library. I would suggest you to use a divider directly in your row layouts to circumvent this behaviour.

Something like this should do the trick:
```
<View
    layout_width="match_parent"
    layout_height="1dp"
    background="@color/brown" />
```

**Comment by tir38** [comment]
Yeah that's what I had to do. Thanks for the quick reply.
