### ISSUE TITLE
Please consider removing android:allowBackup="true" from library Manifest

### ISSUE THREAD

**Issue by erikpedersen** [bgogetap/StickyHeaders#33]
Having the android:allowBackup="true" attribute in the library Manifest forces projects using this library to override this value using the tools:replace in the main project <application> section if the project referencing this library has the android:allowBackup value set to false. It would be helpful if this was removed from the library Manifest to make the Manifest merge and build process cleaner. Thanks!

**Comment by bgogetap** [comment]
Release in 0.4.2
