### ISSUE TITLE
Dynamically change sticky header

### ISSUE THREAD

**Issue by hadalaba** [bgogetap/StickyHeaders#39]
In my app I dynamically change two TextView with numbers in sticky header by clicking overflow menu (in screenshot). Then I insert a number with length more then 1, and TextView don't display the whole number. Is there another way to fix it? without setting new adapter and StickyLayoutManager, because this way refreshing the whole RecyclerView, and I don't need it :)

TextView has layout_width="wrap_content" parameter
(Sorry for bad language)
![sticky header](https://cloud.githubusercontent.com/assets/20413469/25529556/9f0be8c2-2c5d-11e7-905e-2a25748e4aaa.PNG)

However, one of the simplest process to add sticky header :) great work!

**Comment by bgogetap** [comment]
So the TextView content is being cut off?

**Comment by hadalaba** [comment]
yes, it is

**Comment by bgogetap** [comment]
Sorry for the delay, this is still something I will look into but I've been pretty busy lately.

**Comment by bgogetap** [comment]
Could you please see if this is still an issue in 0.4.8?

Also, is the TextView of your header set to `match_parent` for width?

**Comment by bgogetap** [comment]
Make that 0.4.9. I was able to periodically reproduce what I think your issue is, but it's fixed now (I'm forcing a layout of the Sticky Header view when re-bound).
