### ISSUE TITLE
Sliding fast would make sticky header not work

### ISSUE THREAD

**Issue by xybean** [bgogetap/StickyHeaders#40]
![image](https://cloud.githubusercontent.com/assets/10599887/26661803/9504a458-46b2-11e7-853c-b9aade982554.png)

**Comment by xybean** [comment]
I fixed it by modified this method
![13df5d93-c48c-426e-89a7-bd85221912eb](https://cloud.githubusercontent.com/assets/10599887/26677472/c2f597fe-46fe-11e7-9462-66a0632e1bb1.png)

**Comment by bgogetap** [comment]
Glad you got it resolved. I'll look into adding this into the library. Thanks!
