### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by wman1980** [bgogetap/StickyHeaders#41]
I tried using your lib, but I encountered the following problem:
- I added jCenter() to gradle file under buildscript/repositories
- I added the compile  statement  compile 'com.brandongogetap:stickyheaders:0.4.4' to grade file
=> Suddenly my recycler view stops working and says: E/RecyclerView: No adapter attached; skipping layout

If I revert my gradle file, everything works again.

Don't know whats going wrong here ...

**Comment by bgogetap** [comment]
What version of the support library are you using? I don't see how simply importing this library would cause any changes in an application. The only thing I can see happening is your app now using support lib `25.3.1` if it isn't already on that or a later version. Even then, I'd be surprised if there were some breaking change in the support lib that caused your RecyclerView to not work.

You are adding this to the module's `build.gradle` and not your project's `build.gradle`, right?

If you can give me a way to reproduce this, I'll gladly take a look, but I'm going to assume this is unique issue with your specific project in some way. 

Also, you probably don't need the `jcenter()` declaration, I'm pretty sure Android projects have that defined by default now; I just had it there for completeness.

**Comment by wman1980** [comment]
Thanks for your quick response!

I am using support lib `24.2.1`.
I also added everything to the modules `build.gradle`.

It works if I add your code classes manually to my project.
Unfortunately I have one more question. It seems that your lib does not work if the list has an extra header right before the sticky header items and normal items in the recycler view.
E.g. if I would achieve sticky headers with ItemDecorations the list needs to be uniform. Seems its the same with yours. Is that true? Or is there any workaround?

**Comment by bgogetap** [comment]
Did you figure out if this was an issue with your support library version? Like I said, using this library will automatically update your support lib to 25.3.1 (unless you exclude it in your build.gradle compile statement).

What is an extra header right before the sticky header? What is a "header" that you're referring to if not a sticky header?

I also don't understand what you mean about the list needing to be uniform.

**Comment by bgogetap** [comment]
Please reopen if the issue was not with the support lib version.
