### ISSUE TITLE
How to support a SwipeRefreshLayout?

### ISSUE THREAD

**Issue by ThanosFisherman** [bgogetap/StickyHeaders#42]
Hi, Just came across this neat library and tried to integrate it to my app. My RecyclerView Layout looks like this

```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:tools="http://schemas.android.com/tools"
             android:layout_width="match_parent"
             android:layout_height="match_parent">

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/swipe_refresh_scan"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler_list"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scrollbars="vertical"
            tools:listitem="@layout/item_list_wifi"/>

    </android.support.v4.widget.SwipeRefreshLayout>
</FrameLayout>
```

But when I run  the app I get the following error
`RecyclerView parent must be either a FrameLayout or CoordinatorLayout`

Why must RecyclerView have a FrameLayout or CoordinatorLayout as a parent?
How Am I going to support a SwipeRefreshLayout if that's the case?

**Comment by bgogetap** [comment]
This library works by adding the view that corresponds to the sticky header to the parent ViewGroup of the RecyclerView. This can only be done with ViewGroups that support multiple children and do not arrange child views without specific layout params.

You should be able to have a FrameLayout be the only child of the SwipeRefreshLayout and then have the RecyclerView inside that FrameLayout.

**Comment by ThanosFisherman** [comment]
I also thought about doing it the way you suggest but It won't work with my current layout arrangement.
The layout above is a child of a view pager which is a child of a Coordinator Layout. 
Now If I make the SwipeRefreshLayout wrap FrameLayout and its child RecyclerView. The contents of Recycler view dissapear for as long as the SwipeRefreshLayout is animating. Have a look at the attached video. Could it be a SwipeRefreshLayout bug? I'm not sure.
![ezgif com-apng-to-gif](https://user-images.githubusercontent.com/4888330/27769956-cf3a4d68-5f3e-11e7-803a-38ccb419da4f.gif)

**Comment by ThanosFisherman** [comment]
I managed to work around that flickering issue by modifying my above layout as follows

```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:tools="http://schemas.android.com/tools"
             android:layout_width="match_parent"
             android:layout_height="match_parent">

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/swipe_refresh_scan"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recycler_list"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:scrollbars="vertical"
                tools:listitem="@layout/item_list_wifi"/>

        </FrameLayout>


    </android.support.v4.widget.SwipeRefreshLayout>
</FrameLayout>
```
I have no idea why this works. Well at least my issue is solved for now.
