### ISSUE TITLE
Header jumps when user scroll up and higer header have more text than lower

### ISSUE THREAD

**Issue by PiotrBandurski** [bgogetap/StickyHeaders#44]
Hi!
At first I would like to thank you for this super library :) I found a little bug which makes glitch as mentioned in title. To reproduce just replace `com.brandongogetap.stickyheaders.demo.MainActivity#compileItems` method with this code:

`    private static boolean doubler;
    private List<Item> compileItems() {
        List<Item> items = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            if (i == 2 || (i % 4 == 0 && i > 0)) {
                doubler = !doubler;
                if (doubler) {
                    items.add(new HeaderItem("Header at " + i, "header text header text header text header text header text header text header text header text header text"));
                }else {
                    items.add(new HeaderItem("Header at " + i, "header text"));
                }
            } else {
                items.add(new Item("Item at " + i, "Item description at " + i));
            }
        }
        return items;
    }`

and then scroll to bottom and slowly scroll up. If this is not enough I can make a little video with this. Can I ask if this is little effort for you and can you fix this easily or I should fix it myself and then make pull request?
Thanks!

**Comment by bgogetap** [comment]
Thanks for the sample code. I see what you mean.

I will look into maybe playing with visibility timing or something.

**Comment by PiotrBandurski** [comment]
Yea, I made a fast fix because I need sticky headers asap :P. When official fix will be avaiable I will use your changes :)

**Comment by bgogetap** [comment]
Got this figured out I think. Will release fix in new version within the next few hours hopefully.
