### ISSUE TITLE
Headers are not in proper possition when user scroll very fast

### ISSUE THREAD

**Issue by PiotrBandurski** [bgogetap/StickyHeaders#47]
Hi,
I noticed another issue: when there are few headers and user scroll very fast then header is on higher position. This looks like that:
![](https://im.ezgif.com/tmp/ezgif-1-2193873032.gif)
Code I'm using:

`    private List<Item> compileItems() {
        List<Item> items = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            if (i == 2 || (i % 50 == 0 && i > 0)) {
                items.add(new HeaderItem("Header at " + i, ""));
            } else {
                items.add(new Item("Item at " + i, "Item description at " + i));
            }
        }
        return items;
    }`

**Comment by bgogetap** [comment]
I'm unable to see the image you attached, but I was able to reproduce this with your sample code and think I have a fix for it.

**Comment by bgogetap** [comment]
I'm going to try to fix another bug or two before putting this fix in a release.
