### ISSUE TITLE
Header Layout is not refreshed when adapter data changed

### ISSUE THREAD

**Issue by FredDev06** [bgogetap/StickyHeaders#49]
Hi there ! :) 
First of all, you've done a great job with this library, one of simplest way to implement Sticky Headers. 

I just noticed a small issue but a bit annoying for my use case.
When the adapter data change (like using adapter filters) if the position of the current header is the same than the new one (after data has been filtered), you do NOT rebind the header layout.

I just modified the code of StickyHeaderPositioner.java and made the following modification as a workaround:

```
 void reset(int orientation, int firstVisiblePosition) {
        this.orientation = orientation;
        // Don't reset/detach if same header position is to be attached
        if (getHeaderPositionToShow(firstVisiblePosition, null) == lastBoundPosition) {
            // I JUST ADDED THE FOLLOWING LINE TO FORCE THE REBIND OF THE NEW HEADER LAYOUT
            updateCurrentHeader = true;
            return;
        }
        if (fallbackReset) {
            lastBoundPosition = INVALID_POSITION;
        }
    }
```

I did not find any side effect yet and I would like to have your opinion about this. 
Thanks for your great work anyway.

**Comment by bgogetap** [comment]
Hmm, I would have thought the data listener on the adapter (which sets `updateCurrentHeader` to `true`), followed by the call to `StickyHeaderPositioner#updateHeaderState` from the LayoutManager would have caught that. I'm guessing since the data change observers are in a list, the observer in `StickyHeaderPositioner` is being called after the observer that triggers `LayoutManager#onLayoutChildren`. 

I could probably ditch the adapter change observer and just use your change but I want to see if there is any way I can optimize not re-binding if unnecessary. However I think that'd be a very small optimization at best, so I might just go with always re-binding an existing header after a layout which is what your change will do.

I'll look at it tonight and get a release out today or tomorrow.

Good catch, thanks!

**Comment by bgogetap** [comment]
So I just slightly modified my sample -- On item click I remove item at position 2, then add a new header item at position 2 with different values. After scrolling until the header at position 2 is stickied, I click an item and the new values show on the already bound header.

Can you think of any reason why it wouldn't be working in your case?

Anyway, I might still go with your change but I don't like not being able to reproduce an issue.

**Comment by ivan-ontruck** [comment]
Hi @bgogetap . Thanks for the lib, it is just awesome. 
I have the same issue described by @FredDev06. I can reproduce it with a simple two items list: one header at pos 0 and one content item at pos 1. I use diffUtil to update the recyclerview. When I make the two items data change, only the content one is being updated; the header doesn't get updated.

Thanks again!

**Comment by bgogetap** [comment]
I was able to reproduce the issue, thanks guys.

I think the attempt at optimization I'm making by not rebinding the same header isn't worth the effort to try to keep, so I was able to remove a bit of fluff. Release 0.4.8 imminent.

**Comment by ivan-ontruck** [comment]
@bgogetap I think your fix broke something else: using 0.4.8 I've noticed that existing headers doesn't get removed when the dataset is updated to an empty list of items.

I can reproduce it with a simple two items list: one header at pos 0 and one content item at pos 1. I use diffUtil to update the recyclerview. When I update the recyclerview with an empty list, only the content one is being removed; the header remains there.

**Comment by ThanosFisherman** [comment]
@ivan-ontruck Yes you are right indeed. Here is a sample that reproduces what you are saying.
https://github.com/ThanosFisherman/StickyHeaders
press "REMOVE 4" menu twice. It is supposed to remove everything from the list yet the very last header won't be removed.

**Comment by bgogetap** [comment]
Thanks all, and sorry for the issues.

I'm going to release a fix tonight along with a much needed update to the UI tests so things like this are hopefully avoided in the future.

**Comment by bgogetap** [comment]
Alright, 0.4.9 is released.

Updated to use DiffUtil in the Adapter when data changes as well, so hopefully this more closely matches users' setups.

Several UI were tests added as well.

Sorry again for the regressions and I really appreciate the reports. 

Please don't hesitate to tell me what else I broke!
