### ISSUE TITLE
sticky header with background not working 

### ISSUE THREAD

**Issue by engr-erum** [bgogetap/StickyHeaders#50]
I followed below code but my header is not sticky and even its not showing any background color in UI.

List<Item> items = compileItems();
        RecyclerAdapter adapter = new RecyclerAdapter(items);
        StickyLayoutManager layoutManager = new TopSnappedStickyLayoutManager(this, adapter);
        layoutManager.elevateHeaders(true);
        layoutManager.elevateHeaders(10);
        rvHeader.setLayoutManager(layoutManager);
        rvHeader.setAdapter(adapter);

  private List<Item> compileItems() {
        List<Item> items = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            if (i == 2 || (i % 4 == 0 && i > 0)) {
                items.add(new HeaderItem("Header at " + i, ""));
            } else {
                items.add(new Item("Item at " + i, "Item description at " + i));
            }
        }
        return items;
    }

public class RecyclerAdapter  extends RecyclerView.Adapter<RecyclerAdapter.BaseViewHolder>  implements StickyHeaderHandler {

    @Override
    public List<Item> getAdapterData() {
        return data;
    }

    private final List<Item> data;

    RecyclerAdapter(List<Item> data) {
        this.data = data;
    }

    @Override
    public BaseViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = from(parent.getContext()).inflate(R.layout.item_view, parent, false);
        final BaseViewHolder viewHolder;
        if (viewType == 0) {
            viewHolder = new MyViewHolder(view);
        } else {
            viewHolder = new MyOtherViewHolder(view);
        }
        view.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) {
                // This is unsafe to do in OnClickListeners attached to sticky headers. The adapter
                // position of the holder will be out of sync if any items have been added/removed.
                // If a click listener needs to be set on a sticky header, it is recommended to identify the header
                // based on its backing model, rather than position in the data set.
                int position = viewHolder.getAdapterPosition();
                if (position != NO_POSITION) {
                    data.remove(position);
                    notifyDataSetChanged();
                }
            }
        });
        return viewHolder;
    }

    @Override
    public void onBindViewHolder(BaseViewHolder holder, int position) {
        Item item = data.get(position);
        holder.titleTextView.setText(item.title);
        holder.messageTextView.setText(item.message);
        if (position != 0 && position % 16 == 0) {
            holder.itemView.setPadding(0, 100, 0, 100);
        } else {
            holder.itemView.setPadding(0, 0, 0, 0);
        }
        if (item instanceof StickyHeader) {
            holder.itemView.setBackgroundColor(Color.CYAN);
        } else {
            holder.itemView.setBackgroundColor(Color.TRANSPARENT);
        }
    }

    @Override public int getItemCount() {
        return data != null ? data.size() : 0;
    }

    @Override public int getItemViewType(int position) {
        if (position != 0 && position % 16 == 0) {
            return 1;
        }
        return 0;
    }

    private static final class MyViewHolder extends BaseViewHolder {

        MyViewHolder(View itemView) {
            super(itemView);
        }
    }

    private static final class MyOtherViewHolder extends BaseViewHolder {

        MyOtherViewHolder(View itemView) {
            super(itemView);
        }
    }

    static class BaseViewHolder extends RecyclerView.ViewHolder {

        TextView titleTextView;
        TextView messageTextView;

        BaseViewHolder(View itemView) {
            super(itemView);
            titleTextView = (TextView) itemView.findViewById(R.id.tv_title);
            messageTextView = (TextView) itemView.findViewById(R.id.tv_message);
        }
    }
}

**Comment by bgogetap** [comment]
I copied your code and it works fine for me.

What does the parent layout of you RecyclerView have going on? If this is just from my sample app and not code from your own app, then I don't know what to say since I don't see any reason why it wouldn't work.

**Comment by bgogetap** [comment]
Closing this. Please feel free to re-open if you can expand on your issue.
