### ISSUE TITLE
Double sticky headers showing at top of screen and start of RV

### ISSUE THREAD

**Issue by ozv101** [bgogetap/StickyHeaders#51]
I have an AppBarLayout which takes up a certain portion of the screen, say 300dp. The RecyclerView starts after that with the first header, but the one header is initially shown at the top of the screen covering the AppBarLayout and another where the RecyclerView starts. It seems like there's always a header on top of the screen, but shouldn't be there until the first header hits the top when scrolling.

```<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:ads="http://schemas.android.com/apk/res-auto"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <LinearLayout
            <!-- Stuff in here -->
        </LinearLayout>

    </android.support.design.widget.AppBarLayout>

    <android.support.v7.widget.RecyclerView
        android:id="@+id/rv"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:clipToPadding="false"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />

</android.support.design.widget.CoordinatorLayout>```

**Comment by bgogetap** [comment]
Is this, as far as you know, a new bug in 0.4.9?

**Comment by ozv101** [comment]
@bgogetap no this is first version i've tried. i see you have 0.4.5 as another release. do you want me to try that or another one?

**Comment by bgogetap** [comment]
No that's not necessary. I'll use your layout and see if I can reproduce this in my sample project.

**Comment by ozv101** [comment]
@bgogetap thanks. let me know if you need any more related code.

**Comment by ozv101** [comment]
@bgogetap any luck with this?

**Comment by bgogetap** [comment]
Sorry for the delay, I haven't had a chance to look into it.

I will try my best this weekend.

**Comment by bgogetap** [comment]
So I the issue here is that the sticky header positioner does not check for insets applied by the parent CoordinatorLayout. The easy fix for this is to wrap the RecyclerView in a FrameLayout and move the appbar_scrolling_view_behavior to that FrameLayout.

I think adding support for checking for insets would be a good change. I will look into it when I get a chance, but the above fix should suffice for now.

**Comment by bgogetap** [comment]
Track status of this bug in #54
