### ISSUE TITLE
not working when recyclerview is put inside a nestedscrollview

### ISSUE THREAD

**Issue by evalo** [bgogetap/StickyHeaders#57]
hi, it seems that when the recyclerview is put inside nestedscrollview, the header is not working anymore?
so i put my recyclerview inside a coordinatorLayout inside a linearlayout inside a nestedscrollview. i tried remove the nestedscrollview and it's working.
is there any way that i can workaround?

**Comment by SanjaGrgurevic** [comment]
@evalo did you find a way to bypass this behaviour because I'm facing the same issue?

**Comment by LeoDroidCoder** [comment]
+1 the same issue

**Comment by LeoDroidCoder** [comment]
Any solutions?
