### ISSUE TITLE
Could not determine artifacts for com.brandongogetap:stickyheaders:0.4.9: Skipped due to earlier error

### ISSUE THREAD

**Issue by hirosz** [bgogetap/StickyHeaders#58]
Is evrything ok with repo? When I try to sync I get error:
Error:Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.brandongogetap:stickyheaders:0.4.9: Skipped due to earlier error

**Comment by hirosz** [comment]
And now it's work like that. I don't know what was the problem

**Comment by bgogetap** [comment]
Glad it worked itself out.

It's on Maven and I never remove old artifacts so maybe it was just a temporary issue.
