### ISSUE TITLE
Update sticky header

### ISSUE THREAD

**Issue by afbarbag** [bgogetap/StickyHeaders#71]
I'm trying to use a TabLayout where the TabLayout is a sticky header. There is no associated ViewPager. Upon clicking a tab, the items in the Adapter are changed and then `notifyItemRangeChanged(tablayoutPosition, listSize)` is called. The TabLayout view never reflects the updated selected tab when the view is being "stuck". But if the RecyclerView is scrolled such that the TabLayout is in it's natural position, the expected tab appears selected.

Is there any way to get the StickyHeader to have an updated view?

**Comment by afbarbag** [comment]
Although if the user clicks

**Comment by bgogetap** [comment]
Next release will have a way to get a reference to the view holder used for the sticky header, but I still suggest finding a different way to keep the view updated as juggling keeping the stickied view holder (if active) updated along with the normal list might be error prone.

**Comment by afbarbag** [comment]
Is there any way to access the view other than through the view holder?

**Comment by bgogetap** [comment]
You can use `StickyHeaderListener`
