### ISSUE TITLE
AAPT: error: <item> inner element must either be a resource reference or empty.

### ISSUE THREAD

**Issue by pedrofsn** [bgogetap/StickyHeaders#82]
Caused by: org.gradle.internal.UncheckedException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
/home/pedrofsn/.gradle/caches/transforms-1/files-1.1/stickyheaders-0.5.0.aar/dfa156be63c5036f11c837f85651bfa0/res/values/values.xml:4:5-58: AAPT: error: <item> inner element must either be a resource reference or empty.

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <dimen name="default_elevation">5dp</dimen>
    <item name="header_view" type="id">header_view</item>
    <string name="app_name">StickyHeaders</string>
</resources>
```

**Comment by bgogetap** [comment]
Please update to the latest version, this was fixed a while back.
