### ISSUE TITLE
Headers paint not header views after few scrolls.

### ISSUE THREAD

**Issue by vlytvyne** [bgogetap/StickyHeaders#91]
### Before scrolling:
![image](https://user-images.githubusercontent.com/44924680/56672311-ebf48200-66be-11e9-91a9-0e6d5317272d.png)
### After few scrolls:
![image](https://user-images.githubusercontent.com/44924680/56672370-04649c80-66bf-11e9-974f-ce18a816116b.png)

**Comment by bgogetap** [comment]
Do you have a project that I can look at? Sample app in repo still looks fine so I'd need to see how the library is used in your case.

**Comment by vlytvyne** [comment]
> Do you have a project that I can look at? Sample app in repo still looks fine so I'd need to see how the library is used in your case.

You can check it out here:
https://github.com/vlytvyne/StickyHeader

**Comment by bgogetap** [comment]
https://github.com/vlytvyne/StickyHeader/blob/master/app/src/main/java/com/example/stickyheader/Adapter.java#L31

You are changing the background color if it's a header, but not changing it back when that view holder is re-bound for a non-header.

Remember, onBindViewHolder can be called on the same view holder multiple times. With your setup as it is, it could be sometimes binding a header, then later binding a non-header.

This isn't an issue with the library.
