### ISSUE TITLE
StickHeader View covers whole screen when it stick at top

### ISSUE THREAD

**Issue by ananth10** [bgogetap/StickyHeaders#96]
Hi ,

I am trying to implement your sticker header library. i have done everything. but when i do scroll up
the sticky header background color covers whole recyclerview. please check attached screenshot and let me whats wrong in this.
![before_stick_at_top](https://user-images.githubusercontent.com/13381242/72987913-520a6300-3e11-11ea-8c38-67893c61581a.png)
![after_stick_at_top](https://user-images.githubusercontent.com/13381242/72987920-58004400-3e11-11ea-936c-99261864c582.png)

**Comment by bgogetap** [comment]
What does your layout hierarchy look like?

The view that is used as a sticky header is created the same way the RecyclerView creates it, by calling `onCreateViewHolder` on your adapter, followed by `onBindViewHolder`. The view from your view holder is then added to the parent of the RecyclerView. 

This is why there is sometimes a need to wrap your RecyclerView that will have sticky headers in a FrameLayout. If your RecyclerView is a child that isn't the full width of the parent, this may happen (though a bit confused on the height filling out).

**Comment by ananth10** [comment]
Hi ,

 Please see code for item xml and recyclerview xml and adapter calss

**STICKY ITEM**
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <TextView
        android:id="@+id/tv_title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textSize="18sp"
        android:text="Title"
        android:textStyle="bold"/>

    <TextView
        android:id="@+id/tv_message"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textSize="16sp"
        android:text="Message"
        android:textStyle="italic"/>
</LinearLayout>`

**RECYCLERVIEW **

`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/rv_workload_summary"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipToPadding="false"
        android:scrollbars="none"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
</FrameLayout>`

**ADAPTER CLASS**

`class StockRoomAdapter(private val list: ArrayList<StockRoomData>, private val sort:Array<String>) :
    RecyclerView.Adapter<StockRoomAdapter.ViewHolder>(), StickyHeaderHandler {
    override fun getAdapterData(): MutableList<*> {
        return list
    }

    companion object {
        val HEADER = 0
        val SORT=1
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
        val inflater = LayoutInflater.from(parent.context)
        return when (viewType) {
            HEADER -> {
                HeaderViewHolder(inflater.inflate(R.layout.work_load, null))
            }
             SORT->{
                 SortViewHolder(inflater.inflate(R.layout.sam,null))
             }
            else -> {
                ItemViewHolder(inflater.inflate(R.layout.stockroom_item, null))
            }
        }
    }

    override fun getItemCount() = list.size

    override fun getItemViewType(position: Int): Int = list[position].type

    @TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR1)
    override fun onBindViewHolder(holder: ViewHolder, position: Int) {
        val context = holder.itemView.context
        var viewType = list[position].type
        val item = list[position]
        when (viewType) {
            HEADER -> {
                val header = holder as HeaderViewHolder

            }
            SORT->{
//                val sortViewHolder = holder as SortViewHolder
//                val adapter1 = ArrayAdapter<String>(context, R.layout.material_spinner_item, sort)
//                sortViewHolder.spinner.setAdapter(adapter1)
//                sortViewHolder.spinner.setText("Priority: High to Low", false)
//                sortViewHolder.spinner.setOnClickListener {
//                    (it as AutoCompleteTextView).showDropDown()
//                }
                **if (item is StickyHeader) {
                    holder.itemView.setBackgroundColor(Color.CYAN)
                } else {
                    holder.itemView.setBackgroundColor(Color.TRANSPARENT)
                }**
            }
            else -> {
                val item=holder as ItemViewHolder
                item.categoryName.text=list[position].categoryName
                item.stockRoomName.text=list[position].stockRoomName
                item.unitCount.text= list[position].unitCount.toString()
            }
        }
    }
    open inner class ViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView)

    inner class HeaderViewHolder(itemView: View) : ViewHolder(itemView){
        val viewDetails:TextView=itemView.findViewById(R.id.tv_view_details)
    }

    inner class SortViewHolder(itemView: View):ViewHolder(itemView){
//        val spinner:AutoCompleteTextView=itemView.findViewById(R.id.my_spinner_dropdown)
    }

    inner class ItemViewHolder(itemView: View) : ViewHolder(itemView){
        val categoryName:TextView=itemView.findViewById(R.id.tv_category_name)
        val stockRoomName:TextView=itemView.findViewById(R.id.tv_stockroom_name)
        val unitCount:TextView=itemView.findViewById(R.id.tv_unit_count)
    }
}`

**Comment by chetdeva** [comment]
This was happening for me while I was using this:
```
LayoutInflater.from(parent.context).inflate(layoutResId, null)
```
It got fixed when I did this:
```
LayoutInflater.from(parent.context).inflate(layoutResId, parent, false)
```

**Comment by bgogetap** [comment]
Closing due to no updates from reporter.

Thanks @chetdeva for a potential reason this could be happening.

Please reopen with a way to verify a repro of the issue if needed.
